function coachContext(){
  const inc=incidents[state.incidentIndex];
  if(!state.started) return {mood:'idle', title:'Hi, I’m ORA', tips:[
    'I will stay with you during the simulation. You can minimise me at any time.',
    'You will learn sustainability by solving In-Service problems — lifecycle, repair, process, sourcing, biodiversity and design.',
    'If you prefer learning by doing, start Mission 01. I will explain the sustainability meaning after every decision.'
  ]};

  const missionTips={
    'INC-01':{
      operational:{idle:['Start with the 96-hour mission constraint. Then compare what each recovery route consumes: stock, time, repair capacity or new supply.','This is lifecycle thinking: the quickest fix and the best long-term system choice are not always the same.','Safety and approved configuration remain non-negotiable. Sustainability never overrides technical assurance.'],thinking:['Before confirming, ask what this option preserves and what it depletes.','A repair or reuse route can conserve lifecycle value, but only if it remains operationally credible.','You can change your selection until you lock it in.'],positive:['You solved the immediate AOG. Now ask what dependency your choice created or removed.','In-Service sustainability includes useful life, repairability, material demand and supply resilience.','Next, move from recovery to prevention: why was the system exposed?']},
      investigation:{idle:['The actuator failure is the event. Your task is to find the controllable reason one failure became a support crisis.','Look for outdated assumptions, missing controls or weak recovery logic.','Preventing recurrence can reduce emergency interventions and avoidable resource demand.'],thinking:['Test the explanation against the evidence. Does it explain the stock emergency, not just the component failure?','A strong root cause points to something the system can actually improve.','Do not default to “hold more stock” unless the evidence proves stock level itself is the real control gap.'],positive:['Good diagnosis. You have moved from symptom to system condition.','That shift is central to sustainable operations: prevent repeated demand instead of repeatedly paying for the same failure.','Now choose one capability that changes the future state.']},
      investment:{idle:['Choose a capability, not another emergency workaround.','Repair capability, stock logic and end-to-end ownership improve different parts of the lifecycle system.','Your budget is finite, so decide which capability creates the strongest long-term optionality.'],thinking:['Ask what this investment will still change in Month 8 or Month 18.','The best investment is not necessarily the one with the largest metric increase today.','Think about prevention, useful life and resilience together.'],positive:['Capability built. The simulator will carry it into later missions.','This is the difference between solving an incident and improving a system.','Watch for the effect of this choice later in the 18-month journey.']}
    },
    'INC-02':{
      operational:{idle:['This queue looks like a capacity problem, but first check where the units are actually waiting.','Sustainability in repair operations includes keeping recoverable components moving instead of defaulting to new replacement demand.','Your immediate goal is to unblock flow without bypassing airworthiness decisions.'],thinking:['Ask whether your choice removes the bottleneck or merely moves it elsewhere.','More replacement parts can hide a process problem while increasing dependence on new supply.','A temporary coordination cell can be useful, but it is not yet a permanent process fix.'],positive:['Now look at what changed: did you use existing repair capability better, or simply bypass it?','Circularity depends on functioning processes. A repairable component has no lifecycle value if it sits waiting for a decision.','Next, find the true queue-forming condition.']},
      investigation:{idle:['The repair benches are available. So why are units still waiting?','Look at ownership, required inputs and decision timing across the handovers.','Process maturity is a sustainability enabler because it helps existing assets return to service efficiently.'],thinking:['Do not confuse visible workload with the location of the bottleneck.','The strongest hypothesis should explain why work stops before hands-on repair begins.','Think end to end: who decides, with what information, by when?'],positive:['You found a decision-flow bottleneck rather than a physical-capacity shortage.','Reducing waiting and rework can improve both readiness and lifecycle performance without buying more hardware.','Now make that improvement persistent.']},
      investment:{idle:['Choose whether to improve visibility, decision ownership or flexible repair capacity.','All three can help, but only some directly address the evidence from this mission.','A sustainable repair loop needs both technical capability and a process that lets work flow.'],thinking:['Ask which investment reduces avoidable waiting at the root of this mission.','Extra capacity is valuable only when the process can feed it with ready-to-repair work.','Prefer evidence-led improvement over reflexively adding resources.'],positive:['Your repair system is now more capable than it was at Month 4.','This is operational circularity: enable safe repair and return-to-service, not just theoretical reparability.','The next mission will test a different dependency — upstream supply.']}
    },
    'INC-03':{
      operational:{idle:['This mission introduces biodiversity through the supply chain, not through a nature-themed score.','The sourcing restriction matters because ecosystem-sensitive upstream conditions can affect permitting, lead time and continuity.','Your immediate task is to protect readiness while buying time for a qualified structural response.'],thinking:['Ask whether your option reduces dependence or simply consumes the existing buffer.','Repair and recovery can reduce immediate demand for new supply while qualification work continues.','Never bypass material qualification because the supply situation is difficult.'],positive:['Now connect sourcing risk to sustainability: traceability and optionality matter because impacts and disruptions can sit several tiers upstream.','A bigger order from the same source can increase the buffer without reducing concentration risk.','Next, identify the controllable exposure behind the disruption.']},
      investigation:{idle:['The external permitting change is the trigger. Your root cause should focus on what made the organisation vulnerable to it.','Look for concentration, missing traceability and lack of qualified alternatives.','Biodiversity-related risk becomes operational when the supply chain cannot see or absorb upstream change.'],thinking:['Ask: if the same external event happened again, which internal weakness would still leave you exposed?','Supplier inventory is a buffer, not a substitute for traceability and qualified optionality.','A strong diagnosis separates external hazard from internal vulnerability.'],positive:['You identified the resilience gap: concentration plus limited upstream visibility.','This is why responsible sourcing and operational resilience can reinforce each other without making vague environmental claims.','Now choose how to reduce that exposure.']},
      investment:{idle:['You can diversify the source, deepen traceability or expand recovery of existing components.','These are different sustainability levers: optionality, visibility and reduced new-material demand.','Choose the capability that best fits the risk you want to reduce.'],thinking:['A second source reduces concentration; traceability improves knowledge; recovery reduces demand. None is a magic solution.','Think about technical qualification, lifecycle value and upstream dependency together.','Your choice will affect the final stress test.'],positive:['You have changed the sourcing-resilience profile of the system.','Biodiversity is being treated here as a real upstream dependency, not as decoration or a marketing claim.','The next mission moves downstream again: recurring failures and design learning.']}
    },
    'INC-04':{
      operational:{idle:['Seven removals in six months is no longer just a sequence of isolated maintenance events.','Sustainability improves when operational evidence is used to reduce recurring demand and extend useful life.','Your immediate response must protect readiness while opening a route to engineering learning.'],thinking:['Ask whether your choice only buffers the symptom or starts converting the pattern into evidence.','More stock can absorb repeated failures without reducing why they happen.','Stopping repair entirely would sacrifice current readiness for a future solution that does not yet exist.'],positive:['Now ask whether this response created a learning loop or only another temporary buffer.','Design and In-Service sustainability are connected: repairability, accessibility and reliability are partly inherited from design choices.','Next, diagnose why the pattern has not triggered structured engineering action.']},
      investigation:{idle:['The repeated removals are visible. The key question is why the organisation keeps closing them one by one.','Look for the missing trigger between In-Service evidence and engineering review.','A sustainable lifecycle system learns across phases instead of treating operation and design as separate worlds.'],thinking:['Do not stop at “technicians should work faster” or “buy more stock”. Those manage consequences.','The strongest root cause should explain why a recurring pattern fails to become structured engineering learning.','Think about governance of evidence, not blame.'],positive:['You found the broken feedback loop.','This is lifecycle thinking at system scale: field evidence should influence future reliability, maintainability and repairability decisions.','Now choose how strongly to reconnect In-Service and design.']},
      investment:{idle:['You can open a structured design review, strengthen failure-pattern analytics or improve repairability within the current support solution.','One is longer-term design leverage, one improves evidence, and one improves today’s repair loop.','Choose based on the balance you want between near-term support and structural lifecycle improvement.'],thinking:['Ask what evidence your investment needs and how quickly its benefit can appear.','Design changes may have high leverage but slower implementation; repairability improvements can deliver nearer-term lifecycle value.','Sustainability is often about sequencing improvements, not picking one perfect action.'],positive:['You have strengthened the Design ↔ In-Service learning loop.','That can reduce repeated interventions and improve how much useful value is extracted from future components and support solutions.','One mission remains: the combined system stress test.']}
    },
    'INC-05':{
      operational:{idle:['This is the final system test. Two AOGs, constrained supply and high repair workload are happening together.','Resilience means retaining several credible recovery routes when conditions worsen at the same time.','Your earlier capabilities are now part of the scenario — use them.'],thinking:['Ask whether your response protects only today’s readiness or also preserves a recovery route for tomorrow.','Using every spare at once can maximise speed while destroying optionality.','Integrated responses are strongest when previous repair, process, sourcing and design capabilities exist.'],positive:['This decision reveals the strategy you built over 18 months.','Sustainability under pressure is about balancing readiness, lifecycle value, process quality and dependency — not maximising one metric.','Next, diagnose what the combined shock says about the system.']},
      investigation:{idle:['Do not call the combined disruption “bad luck”. Resilience exists because variability cannot be eliminated.','Look for the structural property that determines whether the system has choices under pressure.','Think optionality across repair, stock, sourcing, process and engineering.'],thinking:['Inventory is only one buffer. A resilient system has multiple recovery routes and clear decision mechanisms.','The strongest diagnosis should explain why overlapping shocks become manageable or unmanageable.','Focus on system design, not perfect prediction.'],positive:['You identified optionality as the central resilience property.','A sustainable support model is not one that avoids every disruption; it is one that can absorb change without repeatedly exhausting assets and resources.','Now institutionalise what you learned.']},
      investment:{idle:['Your final investment converts lessons into a recurring operating model, lifecycle portfolio or stress-testing routine.','This is where isolated improvements become governance and continuous learning.','Choose what you would want the organisation to keep doing after the simulation ends.'],thinking:['Ask which mechanism will keep challenging assumptions before the next disruption.','Portfolio governance connects lifecycle evidence to investment; stress tests expose hidden dependencies; an operating model clarifies coordinated response.','There is no universal best answer — the final review will show the profile you created.'],positive:['Final capability built. You have completed the 18-month learning journey.','Your result will not be a single sustainability score. It will show the pattern of trade-offs and capabilities you created.','Open the final Sustainability & Readiness Review to see your strategy.']}
    }
  };

  const mission=missionTips[inc?.id];
  if(!mission) return {mood:'idle',title:'Sustainability coach',tips:['Read the operational constraint first.','Connect the decision to lifecycle and system consequences.','Build persistent capability rather than repeating emergency fixes.']};
  const phase=mission[state.phase] || mission.operational;
  const key=state.phase==='operational' ? (state.operationalResolved?'positive':state.selectedOption?'thinking':'idle') : state.phase==='investigation' ? (state.investigationResolved?'positive':state.selectedEvidence?'thinking':'idle') : (state.investmentResolved?'positive':state.selectedInvestment?'thinking':'idle');
  const titles={
    'INC-01':['Lifecycle under pressure','Find the system cause','Build lifecycle resilience'],
    'INC-02':['Make repair flow','Find the queue bottleneck','Turn repair into a capability'],
    'INC-03':['Protect supply without shortcuts','Separate hazard from vulnerability','Reduce upstream dependency'],
    'INC-04':['Turn recurrence into learning','Find the broken feedback loop','Reconnect Design and In-Service'],
    'INC-05':['Use the system you built','Diagnose resilience','Make learning repeatable']
  }[inc.id];
  const phaseIndex={operational:0,investigation:1,investment:2}[state.phase];
  return {mood:key==='positive'?'positive':key==='thinking'?'thinking':'idle',title:titles[phaseIndex],tips:phase[key]||phase.idle};
}

function renderCoachWidget(){
  const ctx=coachContext();
  const tip=ctx.tips[coachTipIndex % ctx.tips.length];
  if(coachMinimized) return `<button class="coach-minimized" id="coachExpand" type="button" aria-label="Open ORA sustainability coach"><span class="coach-pulse"></span>ORA <small>tip</small></button>`;
  return `<aside class="floating-coach" aria-label="ORA interactive sustainability coach">
    <div class="coach-visual-wrap">${renderGuideAvatar('coach',ctx.mood)}</div>
    <div class="coach-bubble">
      <div class="coach-bubble-head"><div><span>ORA · AEROSPACE SUSTAINABILITY COACH</span><strong>${ctx.title}</strong></div><button id="coachMinimize" class="coach-icon-btn" type="button" aria-label="Minimise ORA">—</button></div>
      <p>${tip}</p>
      <div class="coach-actions"><small>TIP ${(coachTipIndex % ctx.tips.length)+1} / ${ctx.tips.length}</small><button id="coachNextTip" type="button">Next tip →</button></div>
    </div>
  </aside>`;
}

function renderLandingCoach(){ return `<div id="coachMount">${renderCoachWidget()}</div>`; }

function bindCoachControls(){
  const min=document.getElementById('coachMinimize');
  if(min) min.onclick=()=>{coachMinimized=true; rerenderCoachOnly();};
  const expand=document.getElementById('coachExpand');
  if(expand) expand.onclick=()=>{coachMinimized=false; rerenderCoachOnly();};
  const next=document.getElementById('coachNextTip');
  if(next) next.onclick=()=>{coachTipIndex++; rerenderCoachOnly();};
}
function rerenderCoachOnly(){
  const mount=document.getElementById('coachMount');
  if(mount){mount.innerHTML=renderCoachWidget();bindCoachControls();}
}
