incidents.push({
    id:"INC-05",
    month:18,
    title:"Readiness shock — Two AOGs, one constrained supplier, one repair queue",
    summary:"The final scenario combines pressures from the previous 18 months. Two aircraft are unavailable, the constrained material source has extended delivery dates, and the repair centre is receiving more work. The options available to you now depend partly on the capabilities you chose to build earlier.",
    data:[["Aircraft AOG","2"],["Mission window","5 DAYS"],["Supplier status","CONSTRAINED"],["Repair workload","HIGH"]],
    constraints:["Recover at least one aircraft within five days","Protect the second aircraft from becoming a long-duration AOG","Technical approval routes remain mandatory","Use the capabilities you have built — or work around the ones you did not"],
    lens:"This is a system test. The question is not whether one emergency action is clever; it is whether earlier planning, repair, sourcing, process and design decisions created enough optionality to absorb simultaneous pressure.",
    broader:"A real cross-functional review may also consider evidence on transport-related CO2, energy use, water, waste or VOCs. In this stress test they remain supporting considerations alongside readiness, lifecycle, supply and process resilience — never the sole objective.",
    operational:[
      {id:"A",title:"Use the resilience playbook: repair, prioritise stock and coordinate engineering",desc:"Combine approved repair, controlled stock allocation and a single cross-functional recovery plan.",tags:["Integrated response","Benefits from prior investments"],delta:{readiness:8,resilience:6,lifecycle:6,process:6,exposure:-3},feedback:"An integrated response uses multiple recovery routes instead of exhausting one buffer. Its effectiveness is amplified by capabilities built earlier."},
      {id:"B",title:"Use all remaining serviceable stock immediately",desc:"Recover both aircraft as fast as possible by consuming the remaining replacement buffer.",tags:["Maximum short-term speed","Future exposure"],delta:{readiness:12,resilience:-12,lifecycle:-5,process:-2,exposure:7},feedback:"You maximise immediate availability but leave the system highly exposed to the next event."},
      {id:"C",title:"Wait for new supplier deliveries",desc:"Avoid further repair and coordination complexity and rely on the replenishment route.",tags:["Simple governance","Long-duration AOG risk"],delta:{readiness:-12,resilience:-7,lifecycle:-4,process:-3,exposure:6},feedback:"The constrained supplier cannot absorb the five-day mission requirement. Earlier resilience options would have mattered most here."},
      {id:"D",title:"Recover one aircraft and deliberately protect the second repair path",desc:"Prioritise the five-day mission while reserving repair capacity and stock to prevent the second AOG from becoming chronic.",tags:["Balanced recovery","Protects optionality"],delta:{readiness:7,resilience:8,lifecycle:5,process:5,exposure:-2},feedback:"You avoid consuming every buffer at once and preserve a route for the second aircraft. This is a controlled trade-off rather than an attempt to optimise a single metric."}
    ],
    investigation:[
      {id:"A",title:"The final shock is caused by bad luck",desc:"Multiple disruptions happened at the same time and therefore no systemic lesson is possible.",correct:false,feedback:"Simultaneous events are uncertain, but resilience exists precisely to reduce dependence on favourable timing."},
      {id:"B",title:"The dominant weakness is lack of optionality across repair, supply and decision flow",desc:"Where earlier capabilities were not built, the final shock exposes dependence on a small number of recovery routes.",correct:true,feedback:"Correct. Resilience is the ability to retain credible options under pressure. The final incident reveals which options your earlier strategy created or left missing."},
      {id:"C",title:"The only issue is insufficient stock",desc:"If more components had been purchased, the final event would be solved.",correct:false,feedback:"Stock is one buffer, but the scenario combines repair, supply and process constraints. Inventory alone does not create a resilient system."},
      {id:"D",title:"The support organisation should eliminate all variability",desc:"The root cause is the existence of uncertain events and changing lead times.",correct:false,feedback:"Variability cannot be eliminated. The controllable objective is to design processes and capabilities that can absorb it."}
    ],
    investments:[
      {id:"resilienceOperatingModel",title:"Institutionalise a resilience operating model",cost:320,desc:"Define triggers, cross-functional recovery roles, component criticality reviews and periodic stress tests.",tags:["System governance","Portfolio view"],delta:{resilience:10,process:10,lifecycle:3,exposure:-3},feedback:"You turn lessons from individual events into a recurring management system."},
      {id:"lifecyclePortfolio",title:"Create a lifecycle improvement portfolio",cost:380,desc:"Prioritise repairability, recovery, obsolescence and material-dependency actions using shared evidence across component families.",tags:["Lifecycle governance","Design + In-Service"],delta:{lifecycle:12,resilience:7,process:6,exposure:-7},feedback:"You create a structured route from operational evidence to lifecycle investment decisions."},
      {id:"supplyStressTests",title:"Run recurring supply-chain stress tests",cost:240,desc:"Test critical components against lead-time shocks, source loss, repair queues and traceability gaps before disruption occurs.",tags:["Anticipation","Lower cost"],delta:{resilience:11,process:7,exposure:-5,lifecycle:2},feedback:"You make resilience proactive by challenging assumptions before the next disruption."}
    ]
  });
